/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlarmBanner: typeof import('./src/components/industrial/AlarmBanner.vue')['default']
    BarChart8Cyl: typeof import('./src/components/industrial/BarChart8Cyl.vue')['default']
    CircleGauge: typeof import('./src/components/industrial/CircleGauge.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FeelerGauge: typeof import('./src/components/controls/FeelerGauge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusCard: typeof import('./src/components/industrial/StatusCard.vue')['default']
    StatusDot: typeof import('./src/components/industrial/StatusDot.vue')['default']
    TelegraphLever: typeof import('./src/components/controls/TelegraphLever.vue')['default']
    TrendChart: typeof import('./src/components/industrial/TrendChart.vue')['default']
    ValueDisplay: typeof import('./src/components/industrial/ValueDisplay.vue')['default']
  }
}
